from pathlib import Path
import os
BASE_DIR=Path(__file__).resolve().parent.parent
FRONTEND_DIR=BASE_DIR/'frontend'; GENERATED_DIR=BASE_DIR/'generated'; PRINT_DIR=BASE_DIR/'print'
ORIGINAL_DIR=GENERATED_DIR/'original'; CORRECTED_DIR=GENERATED_DIR/'corrected'; LANTERNS_DIR=GENERATED_DIR/'lanterns'
for d in [GENERATED_DIR,ORIGINAL_DIR,CORRECTED_DIR,LANTERNS_DIR,PRINT_DIR]: d.mkdir(parents=True,exist_ok=True)
CAMERA_INDEX=int(os.environ.get('LANTERN_CAMERA_INDEX','0'))
CAMERA_WIDTH=int(os.environ.get('LANTERN_CAMERA_WIDTH','3840'))
CAMERA_HEIGHT=int(os.environ.get('LANTERN_CAMERA_HEIGHT','2160'))
CAMERA_FPS=int(os.environ.get('LANTERN_CAMERA_FPS','30'))
CANONICAL_WIDTH=int(os.environ.get('LANTERN_CANONICAL_WIDTH','1600'))
CANONICAL_HEIGHT=round(CANONICAL_WIDTH*297/210)
JPEG_PREVIEW_QUALITY=82; JPEG_MASTER_QUALITY=97; PNG_COMPRESSION=3
REQUIRED_MARKER_IDS=(0,1,2,3); MAX_RECENT_LANTERNS=40
